//
// Created by 33974 on 2025/9/17.
//

#ifndef STM32F407_LM5175_LED_H
#define STM32F407_LM5175_LED_H

#define LED1_ON HAL_GPIO_WritePin(GPIOB, LED1_Pin, GPIO_PIN_SET);
#define LED1_OFF HAL_GPIO_WritePin(GPIOB, LED1_Pin, GPIO_PIN_RESET);
#define LED2_ON HAL_GPIO_WritePin(GPIOB, LED2_Pin, GPIO_PIN_SET);
#define LED2_OFF HAL_GPIO_WritePin(GPIOB, LED2_Pin, GPIO_PIN_RESET);
#define LED3_ON HAL_GPIO_WritePin(GPIOB, LED3_Pin, GPIO_PIN_SET);
#define LED3_OFF HAL_GPIO_WritePin(GPIOB, LED3_Pin, GPIO_PIN_RESET);

#endif //STM32F407_LM5175_LED_H
