// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DEFAULT_H
#define UI_DEFAULT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DEFAULT
extern void ui_DEFAULT_screen_init(void);
extern void ui_DEFAULT_screen_destroy(void);
extern lv_obj_t * ui_DEFAULT;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_FAN;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_VIstaues;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES
extern lv_obj_t * uic_VIstaues;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

