// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_DEBUG = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ACTUALVOLTLabel = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_PIDOUTLabel = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_NEWVOLTLabel = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_DACVLabel = NULL;
lv_obj_t * ui_DEBUGLabel1 = NULL;
lv_obj_t * ui_DEBUGLabel2 = NULL;
// event funtions

// build funtions

void ui_DEBUG_screen_init(void)
{
    ui_DEBUG = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DEBUG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_DEBUG, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DEBUG, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DEBUG, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DEBUG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -78);
    lv_obj_set_y(ui_Label1, -2);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "g_Vout:");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF3A512), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACTUALVOLTLabel = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_ACTUALVOLTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACTUALVOLTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACTUALVOLTLabel, 19);
    lv_obj_set_y(ui_ACTUALVOLTLabel, -1);
    lv_obj_set_align(ui_ACTUALVOLTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ACTUALVOLTLabel, "Vout");
    lv_obj_set_style_text_color(ui_ACTUALVOLTLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ACTUALVOLTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -79);
    lv_obj_set_y(ui_Label23, 26);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "pid_out:");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x3CF61F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIDOUTLabel = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_PIDOUTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PIDOUTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PIDOUTLabel, -90);
    lv_obj_set_y(ui_PIDOUTLabel, 57);
    lv_obj_set_align(ui_PIDOUTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PIDOUTLabel, "Vout");
    lv_obj_set_style_text_color(ui_PIDOUTLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PIDOUTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 38);
    lv_obj_set_y(ui_Label25, 31);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "new_voltage:");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x25C1F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NEWVOLTLabel = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_NEWVOLTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NEWVOLTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NEWVOLTLabel, -36);
    lv_obj_set_y(ui_NEWVOLTLabel, 60);
    lv_obj_set_align(ui_NEWVOLTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NEWVOLTLabel, "Vout");
    lv_obj_set_style_text_color(ui_NEWVOLTLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NEWVOLTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -42);
    lv_obj_set_y(ui_Label27, 86);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "dacv:");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFA4690), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DACVLabel = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_DACVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DACVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DACVLabel, -90);
    lv_obj_set_y(ui_DACVLabel, 89);
    lv_obj_set_align(ui_DACVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DACVLabel, "Vout");
    lv_obj_set_style_text_color(ui_DACVLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DACVLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DEBUGLabel1 = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_DEBUGLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DEBUGLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DEBUGLabel1, -2);
    lv_obj_set_y(ui_DEBUGLabel1, 85);
    lv_obj_set_align(ui_DEBUGLabel1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_DEBUGLabel1, lv_color_hex(0x29FFC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DEBUGLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DEBUGLabel2 = lv_label_create(ui_DEBUG);
    lv_obj_set_width(ui_DEBUGLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DEBUGLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DEBUGLabel2, 45);
    lv_obj_set_y(ui_DEBUGLabel2, 66);
    lv_obj_set_align(ui_DEBUGLabel2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_DEBUGLabel2, lv_color_hex(0x12D4EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DEBUGLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_DEBUG_screen_destroy(void)
{
    if(ui_DEBUG) lv_obj_del(ui_DEBUG);

    // NULL screen variables
    ui_DEBUG = NULL;
    ui_Label1 = NULL;
    ui_ACTUALVOLTLabel = NULL;
    ui_Label23 = NULL;
    ui_PIDOUTLabel = NULL;
    ui_Label25 = NULL;
    ui_NEWVOLTLabel = NULL;
    ui_Label27 = NULL;
    ui_DACVLabel = NULL;
    ui_DEBUGLabel1 = NULL;
    ui_DEBUGLabel2 = NULL;

}
