// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DEBUG_H
#define UI_DEBUG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DEBUG
extern void ui_DEBUG_screen_init(void);
extern void ui_DEBUG_screen_destroy(void);
extern lv_obj_t * ui_DEBUG;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ACTUALVOLTLabel;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_PIDOUTLabel;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_NEWVOLTLabel;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_DACVLabel;
extern lv_obj_t * ui_DEBUGLabel1;
extern lv_obj_t * ui_DEBUGLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

